export const default_options = {
  selector: "",
  language: "en",
  format: "Y-m-d",
  buddha: false,
  range: false,
  range_separator: " - ",
  multiple: false,
  multiple_separator: ", ",
  inline: false,
  mode: "popup",
  inline_container: null,
  lazy_render: true,
  hour_step: 1,
  minute_step: 1,
  second_step: 1,
  time_12h: false,
  close_on_select: true,
  readonly_input: true,
  allow_clear: true,
  show_reset_button: false,
  show_today_button: true,
  reset_label: null,
  z_index: 3000,
  default_hour: 0,
  default_minute: 0,
  default_second: 0,
  week_start: null,
  disable_past: false,
  swipe_navigation: true,
  keyboard_navigation: true,
  min_date: null,
  max_date: null,
  enabled_dates: [],
  disabled_dates: [],
  enabled_ranges: [],
  disabled_ranges: [],
  enabled_date: null,
  disabled_date: null,
  disabled_weekdays: [],
  on_open: null,
  on_close: null,
  on_select: null,
  on_change: null
};
